### ISSUE TITLE
Request for dataset

### ISSUE THREAD

**Issue by zeyuanyin** [zhaoshiji123/LPM#1]
Hi, @zhaoshiji123, thanks for the release of your excellent work. I'd like to know where I can find the dataset. Could you please share or release the dataset as well?

**Comment by zhaoshiji123** [comment]
Hi! We apply the dataset in NIPS2017 competition, you can find the dataset via kaggle (https://www.kaggle.com/c/nips-2017-non-targeted-adversarial-attack).
